# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main2.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class main_ui(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(542, 513)
        self.change_button = QtWidgets.QPushButton(Form)
        self.change_button.setGeometry(QtCore.QRect(50, 380, 431, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.change_button.setFont(font)
        self.change_button.setObjectName("change_button")
        self.start_button = QtWidgets.QPushButton(Form)
        self.start_button.setGeometry(QtCore.QRect(50, 310, 431, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.start_button.setFont(font)
        self.start_button.setObjectName("start_button")
        self.logo_label = QtWidgets.QLabel(Form)
        self.logo_label.setGeometry(QtCore.QRect(20, 20, 500, 191))
        self.logo_label.setObjectName("logo_label")
        self.create_button = QtWidgets.QPushButton(Form)
        self.create_button.setGeometry(QtCore.QRect(50, 450, 431, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.create_button.setFont(font)
        self.create_button.setObjectName("create_button")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Quest Maker"))
        self.change_button.setText(_translate("Form", "Редактировать игру"))
        self.start_button.setText(_translate("Form", "Запустить игру"))
        self.logo_label.setText(_translate("Form", "RPGmaker"))
        self.create_button.setText(_translate("Form", "Создать новую игру"))


class help_ui(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(435, 432)
        self.help = QtWidgets.QTextEdit(Form)
        self.help.setEnabled(True)
        self.help.setGeometry(QtCore.QRect(10, 10, 411, 411))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.help.setFont(font)
        self.help.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.help.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.help.setReadOnly(True)
        self.help.setObjectName("help")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.help.setHtml(_translate("Form",
                                     "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" "
                                     "\"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                     "<html><head><meta name=\"qrichtext\" content=\"1"
                                     "\" /><style type=\"text/css\">\n"
                                     "p, li { white-space: pre-wrap; }\n"
                                     "</style></head><body style=\" font-family:\'MS Shell Dlg 2\
                                     '; font-size:11pt; font-weight:400; font-style:normal;\">\n"
                                     "<p style=\"-qt-paragraph-type:empty; margin-top:0px; "
                                     "margin-bottom:0px; margin-left:0px; margin-right:0px; "
                                     "-qt-block-indent:0; text-indent:0px; font-family:\
                                     'MS Shell Dlg 2\';\"><br /></p></body></html>"))


class game_create_ui(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(441, 241)
        self.create_button = QtWidgets.QPushButton(Form)
        self.create_button.setGeometry(QtCore.QRect(304, 200, 121, 31))
        self.create_button.setObjectName("create_button")
        self.base_name_line = QtWidgets.QLineEdit(Form)
        self.base_name_line.setGeometry(QtCore.QRect(170, 10, 261, 20))
        self.base_name_line.setObjectName("base_name_line")
        self.restart_button_text = QtWidgets.QPlainTextEdit(Form)
        self.restart_button_text.setGeometry(QtCore.QRect(170, 120, 261, 71))
        self.restart_button_text.setObjectName("restart_button_text")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 60, 101, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 150, 16))
        self.label_2.setObjectName("label_2")
        self.game_name_line = QtWidgets.QLineEdit(Form)
        self.game_name_line.setGeometry(QtCore.QRect(170, 60, 261, 20))
        self.game_name_line.setObjectName("game_name_line")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(10, 130, 140, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(10, 90, 140, 20))
        self.label_4.setObjectName("label_4")
        self.start_screen_key_btn = QtWidgets.QLineEdit(Form)
        self.start_screen_key_btn.setGeometry(QtCore.QRect(170, 90, 261, 20))
        self.start_screen_key_btn.setObjectName("start_screen_key_btn")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(10, 30, 150, 16))
        self.label_5.setObjectName("label_5")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Создание игры"))
        self.create_button.setText(_translate("Form", "Создать"))
        self.label.setText(_translate("Form", "Название игры"))
        self.label_2.setText(_translate("Form", "Название для базы данных"))
        self.label_3.setText(_translate("Form", "Текст на кнопке рестарта"))
        self.label_4.setText(_translate("Form", "Ключ начального экрана"))
        self.label_5.setText(_translate("Form", "(без расширения файла)"))


class new_screen_configurator_ui(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(472, 389)
        self.create_btn = QtWidgets.QPushButton(Form)
        self.create_btn.setGeometry(QtCore.QRect(354, 350, 101, 31))
        self.create_btn.setObjectName("create_btn")
        self.key_line = QtWidgets.QLineEdit(Form)
        self.key_line.setGeometry(QtCore.QRect(10, 320, 451, 20))
        self.key_line.setObjectName("key_line")
        self.text_line = QtWidgets.QTextEdit(Form)
        self.text_line.setGeometry(QtCore.QRect(10, 30, 451, 261))
        self.text_line.setObjectName("text_line")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 10, 70, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(10, 300, 70, 13))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Создание экрана"))
        self.create_btn.setText(_translate("Form", "Создать"))
        self.label.setText(_translate("Form", "Текст"))
        self.label_2.setText(_translate("Form", "Ключ*"))


class button_configurator_ui(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(532, 201)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 20, 80, 20))
        self.label.setObjectName("label")
        self.buttonText = QtWidgets.QPlainTextEdit(Form)
        self.buttonText.setGeometry(QtCore.QRect(90, 20, 431, 101))
        self.buttonText.setObjectName("buttonText")
        self.linkBox = QtWidgets.QComboBox(Form)
        self.linkBox.setGeometry(QtCore.QRect(88, 130, 431, 22))
        self.linkBox.setObjectName("linkBox")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(10, 130, 41, 20))
        self.label_2.setObjectName("label_2")
        self.saveButton = QtWidgets.QPushButton(Form)
        self.saveButton.setGeometry(QtCore.QRect(404, 160, 121, 31))
        self.saveButton.setObjectName("saveButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Создание/Редактирование кнопки"))
        self.label.setText(_translate("Form", "Текст кнопки:"))
        self.label_2.setText(_translate("Form", "Ссылка:"))
        self.saveButton.setText(_translate("Form", "Сохранить"))


class screen_configurator_ui(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(809, 724)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(443, 290, 290, 20))
        self.label_2.setObjectName("label_2")
        self.save_button = QtWidgets.QPushButton(Form)
        self.save_button.setGeometry(QtCore.QRect(443, 350, 360, 31))
        self.save_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.save_button.setObjectName("save_button")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(23, 10, 400, 700))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.background_image = QtWidgets.QLabel(self.frame)
        self.background_image.setGeometry(QtCore.QRect(6, 2, 400, 700))
        self.background_image.setText("")
        self.background_image.setObjectName("background_image")
        self.screen_text = QtWidgets.QTextEdit(self.frame)
        self.screen_text.setGeometry(QtCore.QRect(20, 20, 360, 300))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.screen_text.setFont(font)
        self.screen_text.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.screen_text.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.screen_text.setReadOnly(True)
        self.screen_text.setObjectName("screen_text")
        self.button_list = QtWidgets.QListWidget(Form)
        self.button_list.setGeometry(QtCore.QRect(441, 150, 260, 131))
        self.button_list.setObjectName("button_list")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(441, 122, 220, 21))
        self.label_5.setObjectName("label_5")
        self.id_line = QtWidgets.QLineEdit(Form)
        self.id_line.setGeometry(QtCore.QRect(443, 320, 360, 20))
        self.id_line.setObjectName("id_line")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(440, 10, 249, 20))
        self.label_4.setObjectName("label_4")
        self.delete_button = QtWidgets.QPushButton(Form)
        self.delete_button.setGeometry(QtCore.QRect(710, 250, 91, 31))
        self.delete_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.delete_button.setObjectName("delete_button")
        self.add_button = QtWidgets.QPushButton(Form)
        self.add_button.setGeometry(QtCore.QRect(710, 150, 91, 30))
        self.add_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.add_button.setObjectName("add_button")
        self.screen_text_palne = QtWidgets.QPlainTextEdit(Form)
        self.screen_text_palne.setGeometry(QtCore.QRect(441, 40, 360, 71))
        self.screen_text_palne.setObjectName("screen_text_palne")
        self.change_button = QtWidgets.QPushButton(Form)
        self.change_button.setGeometry(QtCore.QRect(710, 200, 91, 30))
        self.change_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.change_button.setObjectName("change_button")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Редактирование экрана"))
        self.label_2.setText(_translate("Form", "Ключ(должен быть оригинальным)*"))
        self.save_button.setText(_translate("Form", "Сохранить"))
        self.label_5.setText(_translate("Form", "Кнопки"))
        self.label_4.setText(_translate("Form", "Текст экрана"))
        self.delete_button.setText(_translate("Form", "Удалить"))
        self.add_button.setText(_translate("Form", "Добавить"))
        self.change_button.setText(_translate("Form", "Редактировать"))


class main_edit_page_ui(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(811, 724)
        self.search_btn = QtWidgets.QPushButton(Form)
        self.search_btn.setGeometry(QtCore.QRect(560, 70, 240, 30))
        self.search_btn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.search_btn.setObjectName("search_btn")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(560, 610, 139, 20))
        self.label.setObjectName("label")
        self.filter_line = QtWidgets.QLineEdit(Form)
        self.filter_line.setGeometry(QtCore.QRect(560, 40, 240, 20))
        self.filter_line.setObjectName("filter_line")
        self.delete_screen_btn = QtWidgets.QPushButton(Form)
        self.delete_screen_btn.setGeometry(QtCore.QRect(560, 250, 240, 31))
        self.delete_screen_btn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.delete_screen_btn.setObjectName("delete_screen_btn")
        self.open_selected_screen_btn = QtWidgets.QPushButton(Form)
        self.open_selected_screen_btn.setGeometry(QtCore.QRect(560, 210, 240, 30))
        self.open_selected_screen_btn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.open_selected_screen_btn.setObjectName("open_selected_screen_btn")
        self.new_screen_btn = QtWidgets.QPushButton(Form)
        self.new_screen_btn.setGeometry(QtCore.QRect(560, 170, 240, 31))
        self.new_screen_btn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.new_screen_btn.setObjectName("new_screen_btn")
        self.name_text_edit = QtWidgets.QLineEdit(Form)
        self.name_text_edit.setGeometry(QtCore.QRect(560, 640, 240, 20))
        self.name_text_edit.setObjectName("name_text_edit")
        self.screen_table = QtWidgets.QTableWidget(Form)
        self.screen_table.setEnabled(True)
        self.screen_table.setGeometry(QtCore.QRect(10, 10, 541, 701))
        self.screen_table.setDragDropOverwriteMode(True)
        self.screen_table.setAlternatingRowColors(True)
        self.screen_table.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.screen_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.screen_table.setGridStyle(QtCore.Qt.SolidLine)
        self.screen_table.setObjectName("screen_table")
        self.screen_table.setColumnCount(2)
        self.screen_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.screen_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.screen_table.setHorizontalHeaderItem(1, item)
        self.screen_table.verticalHeader().setVisible(False)
        self.screen_table.verticalHeader().setHighlightSections(True)
        self.save_button = QtWidgets.QPushButton(Form)
        self.save_button.setGeometry(QtCore.QRect(560, 680, 240, 30))
        self.save_button.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.save_button.setObjectName("save_button")
        self.filter_box = QtWidgets.QComboBox(Form)
        self.filter_box.setGeometry(QtCore.QRect(560, 10, 240, 22))
        self.filter_box.setObjectName("filter_box")
        self.filter_box.addItem("")
        self.filter_box.addItem("")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(560, 550, 199, 20))
        self.label_2.setObjectName("label_2")
        self.restart_name_btn = QtWidgets.QLineEdit(Form)
        self.restart_name_btn.setGeometry(QtCore.QRect(560, 580, 240, 20))
        self.restart_name_btn.setObjectName("restart_name_btn")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Просмотр экранов"))
        self.search_btn.setText(_translate("Form", "Поиск"))
        self.label.setText(_translate("Form", "Название игры:"))
        self.delete_screen_btn.setText(_translate("Form", "Удалить выделенный экран"))
        self.open_selected_screen_btn.setText(_translate("Form", "Открыть выделенный экран"))
        self.new_screen_btn.setText(_translate("Form", "Создать новый экран"))
        item = self.screen_table.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Ключ"))
        item = self.screen_table.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Текст"))
        self.save_button.setText(_translate("Form", "Сохранить"))
        self.filter_box.setItemText(0, _translate("Form", "По ключу"))
        self.filter_box.setItemText(1, _translate("Form", "По тексту"))
        self.label_2.setText(_translate("Form", "Название кнопки рестарта:"))
